# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package and Release

on:
  push:
    tags:
      - "*"

jobs:
  
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.7
      - name: Install Clean
        run: npm ci
      - name: Check Version
        run: python3 scripts/check_version.py  >> $GITHUB_ENV
      - name: Build
        run: npm run build:production
      - name: Bundle
        run: | 
              mv scripts/autoupdate.sh .
              mv scripts/configure.sh .
              mv share/* .
              zip -r ${{ github.event.repository.name }}-release-${{github.ref_name}}.zip . -x "share/*" "scripts/*" "dist/.tsbuildinfo" "node_modules/*" "typings/*" "src/*" ".git/*" ".github/*" "node_modules/*" ".gitignore" "**/*.js.map" "tsconfig.json"
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name}}
          prerelease: ${{ env.is_prerelease }}
          files:  ${{ github.event.repository.name }}-release-${{github.ref_name}}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
           

