# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CI/CD Pipeline

on:
  push:
    tags:
      - "*"

jobs:
  
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Clean
        run: npm ci
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.7
      - name: Build
        run: npm run build:production
      - name: Build Assets
        run: python3 scripts/parse_csv.py
      - name: Remove Unused Files
        run: | 
           rm "dist/.tsbuildinfo"
      - name: Upload Dist
        uses: actions/upload-artifact@v4.6.0
        with:
          name: target_commonjs
          path: dist        
          retention-days: 1
          if-no-files-found: error
     
          
  publish:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Download Dist
      uses: actions/download-artifact@v4
      with:
        name: target_commonjs
        path: dist
    - name: Bundle
      run: zip -r ${{ github.event.repository.name }}-release-${{github.ref_name}}.zip . -x "*.csv" "scripts/*" "dist/.tsbuildinfo" "node_modules/*" "src/*" ".git/*" ".github/*" "node_modules/*" ".gitignore" "tsconfig.json"
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release ${{ github.ref_name}}
        files:  ${{ github.event.repository.name }}-release-${{github.ref_name}}.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps: 
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18
    - name: Install For Production
      run: npm ci --omit=dev
    - name: Remove Unused Files
      run: |
           rm -rf src/ scripts/ .git/ .github/
           rm -f .gitignore .sapphirerc.json *.md tsconfig.json .prettierignore *.csv
    - name: Download Dist
      uses: actions/download-artifact@v4.6.0
      with:
        name: target_commonjs
        path: dist
    - name: Pre Transaction
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: deployer
        key: ${{ secrets.KEY }}
        script: |
                 sudo supervisorctl stop bots:losungsbot
                 sudo /opt/deploy_scripts/chown_losungsbot_deployer.sh
                 sudo /opt/deploy_scripts/cleanup_losungsbot.sh 
    - name: Transaction
      uses: up9cloud/action-rsync@master
      env:
        HOST: ${{ secrets.HOST }}
        USER: deployer
        KEY: ${{ secrets.KEY }}
        TARGET: /var/www/losungsbot
        ARGS: -az --stats --delete
        VERBOSE: true
    - name: Post Transaction
      uses: appleboy/ssh-action@master
      env: 
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      with:
        host: ${{ secrets.HOST }}
        username: deployer
        key: ${{ secrets.KEY }}
        envs: DISCORD_TOKEN, GUILD_ID, CHANNEL_ID
        script: | 
                cd /var/www/losungsbot
                echo "DISCORD_TOKEN=$DISCORD_TOKEN" > .env
                echo "GUILD_ID=$GUILD_ID" >> .env
                echo "CHANNEL_ID=$CHANNEL_ID" >> .env
                sudo /opt/deploy_scripts/chown_losungsbot_mqadmin.sh
                sudo supervisorctl start bots:losungsbot
